export const FETCH_POLLUTION_START = "FETCH_POLLUTION_START";
export const FETCH_POLLUTION_SUCCESS = "FETCH_POLLUTION_SUCCESS";
export const FETCH_POLLUTION_FAIL = "FETCH_POLLUTION_FAIL";

export const FETCH_YEARLY_POLLUTION_START = "FETCH_YEARLY_POLLUTION_START";
export const FETCH_YEARLY_POLLUTION_SUCCESS = "FETCH_YEARLY_POLLUTION_SUCCESS";
export const FETCH_YEARLY_POLLUTION_FAIL = "FETCH_YEARLY_POLLUTION_FAIL";
